Parameters:
  BucketName:
    Type: String
    Description: "The name of the bucket hosting the website"
  BranchName:
    Type: String
    Description: "The branch name that the website's code came from"
Resources:
  Website:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'BucketName'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        RoutingRules:
          -
            RoutingRuleCondition:
              HttpErrorCodeReturnedEquals: 404
            RedirectRule:
              ReplaceKeyWith: index.html
      Tags:
        -
          Key: Name
          Value: !Ref 'BucketName'
        -
          Key: Branch
          Value: !Ref 'BranchName'
